[package]
name = "cucumber_rust"
version = "0.6.1"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "Cucumber testing framework for Rust. Fully native, no external test runners or dependencies."
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/bbqsrc/cucumber-rust"
documentation = "https://docs.rs/cucumber_rust"
homepage = "https://github.com/bbqsrc/cucumber-rust"
edition = "2018"

[badges]
travis-ci = { repository = "bbqsrc/cucumber-rust" }

[[test]]
name = "cucumber"
harness = false

[[test]]
name = "cucumber_builder"
harness = false

[dependencies]
# gherkin = { package = "gherkin_rust", version = "^0.5.1" }
gherkin = { package = "gherkin_rust", git = "https://github.com/bbqsrc/gherkin-rust" }
regex = "1.1.9"
termcolor = "1.0"
pathdiff = "0.1.0"
textwrap = { version = "0.11", features = ["term_size"] }
clap = "2.33.0"
globwalk = "0.7"
shh = "1.0"
runtime = "0.3.0-alpha.6"
futures-preview = "0.3.0-alpha.17"
pin-utils = "0.1.0-alpha.4"
